package minows

import (
	"regexp"
	"strings"

	"github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/host"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/core/protocol"
	ma "github.com/multiformats/go-multiaddr"
	"go.dedis.ch/dela/mino"
	"go.dedis.ch/dela/serde"
	"golang.org/x/xerrors"
)

// Minows implements mino.Mino
// TODO unit tests
type Minows struct {
	myAddr     Address
	segments   []string
	host       host.Host
	rpcsByName map[string]RPC
}

// NewMinows
// listen: local listening address in multiaddress format, e.g. /ip4/0.0.0.0/tcp/80
// public: public dial-able address in multiaddress format, e.g. /dns4/p2p-1.c4dt.dela.org/tcp/443/wss
// identity: Peer ID (multi-hash of public key generated by libp2p)
func NewMinows(listen, public ma.Multiaddr, privKey crypto.PrivKey) (*Minows, error) {
	id, err := peer.IDFromPrivateKey(privKey)
	if err != nil {
		return nil, xerrors.Errorf("could not get Peer ID: %v", err)
	}
	myAddr, err := NewAddress(public, id)
	if err != nil {
		return nil, xerrors.Errorf("could not create address: %v", err)
	}
	// create host & start listening
	// TODO populate peer store with multiaddr & peer IDs of other peers
	h, err := libp2p.New(libp2p.ListenAddrs(listen), libp2p.Identity(privKey))
	if err != nil {
		return nil, xerrors.Errorf("could not create host: %v", err)
	}
	// TODO To stop/shutdown the returned libp2p node, the user needs to cancel the passed context and call `Close` on the returned Host.
	return &Minows{
		myAddr:   myAddr,
		segments: nil,
		host:     h,
	}, nil
}

func (m *Minows) GetAddressFactory() mino.AddressFactory {
	return addressFactory{}
}

func (m *Minows) GetAddress() mino.Address {
	return m.myAddr
}

func (m *Minows) WithSegment(segment string) mino.Mino {
	if segment == "" {
		return m
	}

	return &Minows{
		// TODO host, etc
		myAddr:   m.myAddr,
		segments: append(m.segments, segment),
	}
}

func (m *Minows) CreateRPC(name string, h mino.Handler, f serde.Factory) (mino.RPC, error) {
	pattern := regexp.MustCompile("^[a-zA-Z0-9]+$")
	// validate segments
	if len(m.rpcsByName) == 0 { // no RPC created yet
		for _, seg := range m.segments {
			if !pattern.MatchString(seg) {
				return nil, xerrors.Errorf("invalid segment: %s", seg)
			}
		}
	}
	// validate name
	if !pattern.MatchString(name) {
		return nil, xerrors.Errorf("invalid name: %s", name)
	}
	if _, ok := m.rpcsByName[name]; ok {
		return nil, xerrors.Errorf("already exists rpc: %s", name)
	}
	uri := strings.Join(append(m.segments, name), "/")
	// TODO wrap mino.Handler in network.StreamHandler
	// m.host.SetStreamHandler(identity, h)
	return RPC{
		uri: protocol.ID(uri),
	}, nil
}
